name: Trigger auto deployment for continuous-deployment-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'TodoApp.Frontend/DockerFile/**'
    - '.github/workflows/continuous-deployment-test-app-AutoDeployTrigger-b47562eb-776e-426d-9072-7202ac5743c9.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/TodoApp.Frontend/DockerFile 
          registryUrl: docker.io
          registryUsername: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTINUOUSDEPLOYMENTTESTAPP_REGISTRY_PASSWORD }}
          containerAppName: continuous-deployment-test-app
          resourceGroup: continuous-deployment-tests-rg
          imageToBuild: mon0462/continuous-deployment-test-app:${{ github.sha }}
          dockerfilePath: Dockerfile


